// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALHVi9E56qppSX-B9Qlj_6AD_okRtvfoI',
    appId: '1:829260457406:web:136e1be0f2384566b705ef',
    messagingSenderId: '829260457406',
    projectId: 'login-7f06d',
    authDomain: 'login-7f06d.firebaseapp.com',
    storageBucket: 'login-7f06d.firebasestorage.app',
    measurementId: 'G-LNBZRLCKQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcrw-oCpLNtq_x4dK-DX_Tn6wsYRO44IA',
    appId: '1:829260457406:android:56af69c8d475f876b705ef',
    messagingSenderId: '829260457406',
    projectId: 'login-7f06d',
    storageBucket: 'login-7f06d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPiMer9530_QWvD-HPtSb8hxVHAIMNkfU',
    appId: '1:829260457406:ios:0cfb5b3f4f97ffccb705ef',
    messagingSenderId: '829260457406',
    projectId: 'login-7f06d',
    storageBucket: 'login-7f06d.firebasestorage.app',
    androidClientId: '829260457406-bfd1fpmg7b5c41hi2cmum57sdvm67m12.apps.googleusercontent.com',
    iosClientId: '829260457406-ci36427m1unfo5qvempj6u4miis5fo51.apps.googleusercontent.com',
    iosBundleId: 'com.example.rapidpulseMy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPiMer9530_QWvD-HPtSb8hxVHAIMNkfU',
    appId: '1:829260457406:ios:0cfb5b3f4f97ffccb705ef',
    messagingSenderId: '829260457406',
    projectId: 'login-7f06d',
    storageBucket: 'login-7f06d.firebasestorage.app',
    androidClientId: '829260457406-bfd1fpmg7b5c41hi2cmum57sdvm67m12.apps.googleusercontent.com',
    iosClientId: '829260457406-ci36427m1unfo5qvempj6u4miis5fo51.apps.googleusercontent.com',
    iosBundleId: 'com.example.rapidpulseMy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALHVi9E56qppSX-B9Qlj_6AD_okRtvfoI',
    appId: '1:829260457406:web:598c1205b7f42a3eb705ef',
    messagingSenderId: '829260457406',
    projectId: 'login-7f06d',
    authDomain: 'login-7f06d.firebaseapp.com',
    storageBucket: 'login-7f06d.firebasestorage.app',
    measurementId: 'G-07DWGLT1B0',
  );
}
